name: Build

on:
  workflow_dispatch:
    inputs:
      build_variant:
        description: 'Build variant to test'
        default: 'treble_arm64_bgN'
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Cleanup
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - name: Setup Environment
        run: |
          git lfs install
          git config --global user.name "Alberto Ponces"
          git config --global user.email "ponces26@gmail.com"
          mkdir -p ${{ github.workspace }}/aosp

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ./aosp/treble_aosp

      - name: Build ROM
        run: ./treble_aosp/build.sh
        env:
          OUTPUT_DIR: ${{ github.workspace }}/output
        working-directory: ${{ github.workspace }}/aosp

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.build_variant }}
          path: ${{ github.workspace }}/output/*.xz
