name: Build

on:
  workflow_dispatch:
    inputs:
      build_variant:
        description: 'Build variant to test'
        default: 'treble_arm64_bgN'
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VENDOR_PONCES_PRIV_KEY }}

      - name: Build Image
        run: |
          docker build . --file build/Dockerfile \
                         --target treblebuild \
                         --tag ponces/treblebuild

      - name: Build ROM
        run: |
          mkdir ${{ github.workspace }}/output
          ssh-keyscan github.com > ${{ github.workspace }}/known_hosts
          docker run --rm \
                     --privileged \
                     --name trebletest \
                     --user $(id -u):$(id -g) \
                     --env OUTPUT_DIR=/output \
                     --env BUILD_VARIANT=${{ inputs.build_variant }} \
                     --env SSH_AUTH_SOCK=/ssh-agent \
                     --volume $SSH_AUTH_SOCK:/ssh-agent \
                     --volume ${{ github.workspace }}/output:/output \
                     --volume ${{ github.workspace }}/known_hosts:/home/ubuntu/.ssh/known_hosts \
                     ponces/treblebuild

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.build_variant }}
          path: ${{ github.workspace }}/output/*.xz
