name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VENDOR_PONCES_PRIV_KEY }}

      - name: Setup Environment
        run: echo "RELEASE_TITLE=$(date +'v%Y.%m.%d')" >> $GITHUB_ENV

      - name: Build Image
        run: |
          docker build . --file build/Dockerfile \
                         --target treblebuild \
                         --tag ponces/treblebuild

      - name: Build ROM
        run: |
          mkdir ${{ github.workspace }}/output
          ssh-keyscan github.com > ${{ github.workspace }}/known_hosts
          docker run --rm \
                     --privileged \
                     --name treblebuild \
                     --user $(id -u):$(id -g) \
                     --env OUTPUT_DIR=/output \
                     --env SSH_AUTH_SOCK=/ssh-agent \
                     --volume $SSH_AUTH_SOCK:/ssh-agent \
                     --volume ${{ github.workspace }}/output:/output \
                     --volume ${{ github.workspace }}/config/ota.json:/work/treble_aosp/config/ota.json \
                     --volume ${{ github.workspace }}/known_hosts:/home/ubuntu/.ssh/known_hosts \
                     ponces/treblebuild

      - name: Upload OTA
        uses: actions/upload-artifact@v4
        with:
          name: ota
          path: ${{ github.workspace }}/config/ota.json

      - name: Upload ROM
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/output/*.xz
          title: ${{ env.RELEASE_TITLE }}
          tag_name: ${{ env.RELEASE_TITLE }}
          body: "## Changelog\n- ...\n\n## Notes\n- ..."
          draft: true
          prerelease: false
